#1. Importing required libraries

In [4]:
import pandas as pd
import numpy as np

#2. Reading the dataset

In [5]:
df=pd.read_csv('dirty_cafe_sales.csv')
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07



*   Dataset contains 10,000 rows and 8 columns of cafe sale transactions

#3. Identfying data info and description

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB



*   Most columns contain empty (NaN) values, except for "Transaction ID"
*   "Quantity", "Price Per Unit", and "Total Spent" are being read as text (object) instead of numbers (float)

In [7]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_9226047,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

#4. Dropping initial duplicates

In [8]:
#identifying duplicate rows
print(f"Number of duplicate rows before removal: {df.duplicated().sum()}")

#removing duplicate rows
df.drop_duplicates(inplace=True)
print(f"Number of duplicate rows after removal: {df.duplicated().sum()}")

#checking dataframe
df.info()

Number of duplicate rows before removal: 0
Number of duplicate rows after removal: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

#5. Converting "Quantity", "Price Per Unit", and "Total Spent" into numeric values (float)

#5.1 Converting "Price Per Unit"

In [9]:
#establishing price list
item_price = {
    'Coffee': 2.0,
    'Tea': 1.5,
    'Sandwich': 4.0,
    'Salad': 3.0,
    'Cake': 3.0,
    'Cookie': 1.0,
    'Smoothie': 4.0,
    'Juice': 3.0
}

#reverse mapping price to item
price_item = {price: item for item, price in item_price.items()}

#fill missing 'Item' values based on 'Price Per Unit'
df['Item'] = df['Item'].fillna(df['Price Per Unit'].map(price_item))

#replacing 'ERROR' and 'UNKNOWN' values
df['Price Per Unit'] = df['Price Per Unit'].replace(['ERROR', 'UNKNOWN'], np.nan)

#coverting column into float type
df['Price Per Unit']=df['Price Per Unit'].astype(float)

#checking dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(1), object(7)
memory usage: 625.1+ KB



*   Price for each item is validated (Cookie \$1, Tea \$1.5, Coffee \$2, Salad, Cake, & Juice \$3, and Sandwich & Smoothie \$4)
*   Items listed as 'ERROR' and 'UNKNOWN' were replaced as empty (NaN) values
*   Column has been converted to float type after removing any texts

#5.2 Converting "Total Spent"

In [10]:
#replacing 'ERROR' and 'UNKNOWN' values
df['Total Spent'] = df['Total Spent'].replace(['ERROR', 'UNKNOWN'], np.nan)

#coverting column into float type
df['Total Spent']=df['Total Spent'].astype(float)

#checking dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(2), object(6)
memory usage: 625.1+ KB

#5.3 Converting "Quantity"

In [11]:
#replacing 'ERROR' and 'UNKNOWN' values
df['Quantity'] = df['Quantity'].replace(['ERROR', 'UNKNOWN'], np.nan)

#coverting column into float type
df['Quantity']=df['Quantity'].astype(float)

#checking dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB

#6. Filling empty values in numeric (float) columns

#6.1 Filling "Price Per Unit" empty values

In [12]:
#dividing 'total spent' & 'quantity'
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Total Spent']/df['Quantity'])

#checking dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9962 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB



*   Divided values from "Total Spent" and "Quantity" to find missing "Price Per Unit" values

In [13]:
#filling 'Item' values from mapped price list
df['Item'] = df['Item'].fillna(df['Price Per Unit'].map(price_item))

#checking dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9960 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9962 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB



*   Values listed as "Item" were replaced by their corresponding "Price Per Unit"

In [14]:
#filling empty 'Price Per Unit' values based on 'Item' name
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Item'].map(item_price))

#checking dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9960 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9994 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB



*   Other missing values are filled based on mapped "Item" prices

#6.2 Filling "Total Spent" empty values

In [15]:
#multiplying 'quantity' & 'price per unit'
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity']*df['Price Per Unit'])

#checking dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9960 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9994 non-null   float64
 4   Total Spent       9977 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB



*   Multiplied values from "Quantity" and "Price Per Unit" to find missing "Total Spent" values

#6.3 Filling "Quantity" empty values

In [16]:
#dividing 'total spent' & 'price per unit'
df['Quantity'] = df['Quantity'].fillna(df['Total Spent']/df['Price Per Unit']).round()

#checking dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9960 non-null   object
 2   Quantity          9977 non-null   float64
 3   Price Per Unit    9994 non-null   float64
 4   Total Spent       9977 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB



*   Divided values from "Total Spent" and "Price Per Unit" to find missing "Quantity" values

#7. Transforming "ERROR", "UNKNOWN", and empty values in text (object) columns

#7.1 Transforming "ERROR", "UNKNOWN", and empty values in "Item" column

In [17]:
#replacing 'ERROR' and 'UNKNOWN' values
df['Item'] = df['Item'].replace(['ERROR', 'UNKNOWN'], np.nan)

#identifying $1, $1.5, and $2 items
mask = df['Item'].isna() & ~df['Price Per Unit'].isin([3.0, 4.0])
df.loc[mask, 'Item'] = df.loc[mask, 'Price Per Unit'].map(price_item)

#categorizing empty 'Item' values with 'Price Per Unit' of 3 as '$3 Item'
mask_3_item = df['Item'].isna() & (df['Price Per Unit'] == 3.0)
df.loc[mask_3_item, 'Item'] = '$3 Item'

#categorizing empty 'Item' values with 'Price Per Unit' of 4 as '$4 Item'
mask_4_item = df['Item'].isna() & (df['Price Per Unit'] == 4.0)
df.loc[mask_4_item, 'Item'] = '$4 Item'

#categorizing empty 'Item' values with 'Price Per Unit' of 5 as '$5 Item'
mask_5_item = df['Item'].isna() & (df['Price Per Unit'] == 5.0)
df.loc[mask_5_item, 'Item'] = '$5 Item'

#checking dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9994 non-null   object
 2   Quantity          9977 non-null   float64
 3   Price Per Unit    9994 non-null   float64
 4   Total Spent       9977 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB



*   Missing items are identified based on their specific "Price Per Unit"
*   Items with "Price Per Unit" of \$3 and \$4 are categorized as "\$3 Item" and "\$4 Item", respectively, due to several items sharing the same "Price Per Unit"
*   Items with "Price Per Unit" of \$5 is categorized as "\$5 Item" due to no specific item name

#7.2 Transforming "ERROR", "UNKNOWN", and empty values in "Payment Method" column

In [18]:
#replacing 'ERROR' and 'UNKNOWN' values
df['Payment Method'] = df['Payment Method'].replace(['ERROR', 'UNKNOWN'], np.nan)

#filling empty values with 'Unknown'
df['Payment Method'] = df['Payment Method'].fillna('Unknown')

#checking dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9994 non-null   object
 2   Quantity          9977 non-null   float64
 3   Price Per Unit    9994 non-null   float64
 4   Total Spent       9977 non-null   float64
 5   Payment Method    10000 non-null  object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB



*   "ERROR", "UNKNOWN", and empty values are categorized to "Unknown"

#7.3 Transforming "ERROR", "UNKNOWN", and empty values in "Location" column

In [19]:
#replacing 'ERROR' and 'UNKNOWN' values
df['Location'] = df['Location'].replace(['ERROR', 'UNKNOWN'], np.nan)

#filling empty values with 'Unknown'
df['Location'] = df['Location'].fillna('Unknown')

#checking dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9994 non-null   object
 2   Quantity          9977 non-null   float64
 3   Price Per Unit    9994 non-null   float64
 4   Total Spent       9977 non-null   float64
 5   Payment Method    10000 non-null  object
 6   Location          10000 non-null  object
 7   Transaction Date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB



*   "ERROR", "UNKNOWN", and empty values are categorized to "Unknown"

#7.4 Transforming "ERROR", "UNKNOWN", and empty values in "Transaction Date" column

In [20]:
#replacing 'ERROR' and 'UNKNOWN' values
df['Transaction Date'] = df['Transaction Date'].replace(['ERROR', 'UNKNOWN'], np.nan)

#filling empty values with 'Unknown'
df['Transaction Date'] = df['Transaction Date'].fillna('Unknown')

#checking dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9994 non-null   object
 2   Quantity          9977 non-null   float64
 3   Price Per Unit    9994 non-null   float64
 4   Total Spent       9977 non-null   float64
 5   Payment Method    10000 non-null  object
 6   Location          10000 non-null  object
 7   Transaction Date  10000 non-null  object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB



*   "ERROR", "UNKNOWN", and empty values are categorized to "Unknown"

#8. Removing incomplete records

In [21]:
#removing rows with empty values
df.dropna(subset=['Total Spent'], inplace=True)

#checking dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9977 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9977 non-null   object
 1   Item              9974 non-null   object
 2   Quantity          9974 non-null   float64
 3   Price Per Unit    9974 non-null   float64
 4   Total Spent       9977 non-null   float64
 5   Payment Method    9977 non-null   object
 6   Location          9977 non-null   object
 7   Transaction Date  9977 non-null   object
dtypes: float64(3), object(5)
memory usage: 701.5+ KB



*   Removed rows where "Total Spent" was empty, as they provide no financial value
*   Retained all rows with a "Total Spent" value even if other columns are incomplete to ensure the final total revenue remains accurate

#9. Checking for duplicates

In [22]:
#identifying duplicate rows
print(f"Number of duplicate rows before removal: {df.duplicated().sum()}")

#removing duplicate rows
df.drop_duplicates(inplace=True)
print(f"Number of duplicate rows after removal: {df.duplicated().sum()}")

#checking dataframe
df.info()

Number of duplicate rows before removal: 0
Number of duplicate rows after removal: 0
<class 'pandas.core.frame.DataFrame'>
Index: 9977 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9977 non-null   object
 1   Item              9974 non-null   object
 2   Quantity          9974 non-null   float64
 3   Price Per Unit    9974 non-null   float64
 4   Total Spent       9977 non-null   float64
 5   Payment Method    9977 non-null   object
 6   Location          9977 non-null   object
 7   Transaction Date  9977 non-null   object
dtypes: float64(3), object(5)
memory usage: 701.5+ KB

#10. Saving cleaned data

In [23]:
df.to_csv('clean_cafe_sales.csv', index=False)